version: "3.8"
services:
  postgres:
    image: postgres:10
    container_name: java-postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/data
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_DB=itlab'
  app:
    image: java-app
    container_name: java-app
    restart: always
    ports:
      - "8081:8081"
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_DB=itlab'

volumes:
  data: {}

networks:
  default:
    name: postgres_network