server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: producer
          uri: http://producer
          predicates:
            - Path=/producer/**
        - id: restaurant
          uri: http://restaurant
          predicates:
            - Path=/restaurant/**