server:
  port: 8082
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8888/eureka
spring:
  application:
    name: producer
  jackson:
    serialization:
      indent_output: true
  datasource:
    url: 'jdbc:postgresql://localhost:5432/itlab'
    username: 'postgres'
    password: 'root'
    hikari:
      catalog: 'public'
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: true
    properties:
      hibernate:
        default_schema: 'public'
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    hibernate:
      ddl-auto: create
  main:
    allow-bean-definition-overriding: true
  sql:
    init:
      platform: postgres